spring:
  application:
    name: dollar-order
  datasource:
    url: ${rds.host}
    username: ${rds.username}
    password: ${rds.password}
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  key: ${jwt.secret.key}

kakao:
  api:
    admin-key: ${kakao.api.admin-key}

server:
  port: 8084

destination: ${elk}

aws:
  access:
    key: ${access.key.id}
  secret:
    key: ${aws.secret.key}
